apiVersion: v1
kind: Service
metadata:
  name: recommendation-system
spec:
  selector:
    app: recommendation-system
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: NodePort
